parameters:
  - name: project_key
  - name: project_name

steps:
  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: 'Sonar Cloud GitHub'
      organization: 'healthresearchauthority'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: ${{ parameters.project_key }}
      cliProjectName: ${{ parameters.project_name }}
      extraProperties: |
        sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/test/report-task.txt