parameters:
  - name: project_key
  - name: project_name

steps:
  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: 'Sonar Cloud Connection'
      organization: 'futureiras'
      scannerMode: 'dotnet'
      msBuildVersion: '9.0.2.104486'
      projectKey: ${{ parameters.project_key }}
      projectName: ${{ parameters.project_name }}
      extraProperties: |
        sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml
        sonar.cs.xunit.reportsPaths=$(Build.SourcesDirectory)/**/test_results.xml

  - task: Cache@2
    displayName: Cache SonarScanner
    inputs:
      key: '"SonarScanner" | ".NET" | "$(Agent.OS)"'
      path: '$(Agent.ToolsDirectory)/SonarScanner .NET'