parameters:
  - name: project_key
  - name: project_name

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonar Cloud Connection'
      organization: 'futureiras'
      scannerMode: 'MSBuild'
      projectKey: ${{ parameters.project_key }}
      projectName: ${{ parameters.project_name }}