parameters:
  - name: run_github_security_scan
    type: boolean

stages:
  - stage: Publish
    displayName: Artifact stage
    jobs:
      - job: Publish
        displayName: Push Artifact job
        steps:
          - template: ../steps/nuget/installer.yaml
          - template: ../steps/dotnet/installer.yaml
          - template: ../steps/dotnet/install_report_generator.yaml
          - ${{ if parameters.run_github_security_scan }}:
            - template: ../steps/security/code_scanning_init.yaml
          - template: ../steps/dotnet/restore_from_feed.yaml
          - template: ../steps/dotnet/build.yaml
            parameters:
              checkout: false
          - ${{ if parameters.run_github_security_scan }}:
            - template: ../steps/security/dependency_scanning.yaml
            - template: ../steps/security/code_scanning_analysis.yaml
          - template: ../steps/automationtests/run_unit_tests.yaml
          - template: ../steps/automationtests/publish_code_coverage.yaml
          - template: ../steps/dotnet/pack.yaml
            parameters:
              no_build: true
          - template: ../steps/nuget/push.yaml