parameters:
  - name: run_github_security_scan
    type: boolean
  - name: sonar_project_key
  - name: sonar_project_name

jobs:
  - job: Build
    displayName: Build job
    steps:
      - template: ../steps/nuget/installer.yaml
      - template: ../steps/dotnet/installer.yaml
      - template: ../steps/dotnet/install_report_generator.yaml
      - template: ../steps/dotnet/restore_from_feed.yaml
      - ${{ if parameters.run_github_security_scan }}:
        - template: ../steps/security/code_scanning_init.yaml
      - template: ../steps/codeanalysis/prepare_analysis_configuration.yaml
        parameters:
          project_key: ${{ parameters.sonar_project_key }}
          project_name: ${{ parameters.sonar_project_name }}
      - template: ../steps/dotnet/build.yaml
        parameters:
          checkout: false
      - template: ../steps/codeanalysis/run_code_analysis.yaml
      - template: ../steps/codeanalysis/publish_quality_gate_result.yaml
      - ${{ if parameters.run_github_security_scan }}:
        - template: ../steps/security/dependency_scanning.yaml
        - template: ../steps/security/code_scanning_analysis.yaml
      - template: ../steps/automationtests/run_unit_tests.yaml
      - template: ../steps/automationtests/publish_code_coverage.yaml