parameters:
  - name: run_github_security_scan
    type: boolean
  - name: browser
    displayName: Select a Browser
    type: string
    default: chromium
    values:
      - chromium
      - safari
      - firefox

stages:
  - stage: Build
    condition: and(succeeded(), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'), startsWith(variables['Build.SourceBranch'], 'refs/heads/bug'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main')))
    displayName: Build stage
    jobs:
      - job: "Build"
        displayName: Build job
        variables:
          favouriteSportsTeam: "Houston Rockets"
        steps:
          - template: ../steps/nuget/installer.yaml
          - template: ../steps/dotnet/installer.yaml
          - template: ../steps/dotnet/install_report_generator.yaml
          - ${{ if parameters.run_github_security_scan }}:
            - template: ../steps/security/code_scanning_init.yaml
          - template: ../steps/dotnet/build.yaml
          - ${{ if parameters.run_github_security_scan }}:
            - template: ../steps/security/dependency_scanning.yaml
            - template: ../steps/security/code_scanning_analysis.yaml
          - template: ../steps/automationtests/run_unit_tests.yaml
          - template: ../steps/automationtests/publish_code_coverage.yaml
          - template: ../steps/automationtests/run_e2e_test.yaml
            parameters:
              SportsTeam: $(favouriteSportsTeam)
          - template: ../steps/automationtests/run_api_test.yaml