stages:
  - stage: Build
    condition: and(succeeded(), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'), startsWith(variables['Build.SourceBranch'], 'refs/heads/bug'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main')))
    displayName: Build stage
    jobs:
      - job: "Build"
        displayName: Build job
        steps:
          - template: ../steps/nuget/installer.yaml
          - template: ../steps/dotnet/installer.yaml
          - template: ../steps/dotnet/install_report_generator.yaml
          - template: ../steps/security/code_scanning_init.yaml
          - template: ../steps/dotnet/build.yaml
          - template: ../steps/security/dependency_scanning.yaml
          - template: ../steps/security/code_scanning_analysis.yaml
          - template: ../steps/automationtests/run_unit_tests.yaml
          - template: ../steps/automationtests/publish_code_coverage.yaml
          - template: ../steps/dotnet/publish_artifacts.yaml