parameters:
  - name: install_aspire
    type: boolean
    default: false
  - name: service_defaults_repo
    default: ''
  - name: depends_on
    default: ''

jobs:
  - job: Deploy
    ${{ if ne('', parameters.depends_on) }}:
      dependsOn: ${{ parameters.depends_on }}
      condition: succeeded()
    ${{ if eq('', parameters.depends_on) }}:
      dependsOn: []
    displayName: Deploy
    steps:
      - template: ../steps/nuget/installer.yaml
      - template: ../steps/dotnet/installer.yaml
      - template: ../steps/dotnet/install_report_generator.yaml
      - ${{ if parameters.install_aspire }}:
        - template: ../steps/dotnet/install_aspire_workload.yaml
        - checkout: ${{ parameters.service_defaults_repo }}
      - template: ../steps/dotnet/restore_from_feed.yaml
      - template: ../steps/dotnet/acr_login.yaml
      - template: ../steps/dotnet/publish_container.yaml
      - template: ../steps/dotnet/deploy_aca.yaml