parameters:
  - name: platform
    default: desktop
  - name: browser
    default: chromium
  - name: mobile_os
    default: N/A
  - name: android_device
    default: N/A
  - name: ios_device
    default: N/A
  - name: reportDirectory
    default: test-reports
  - name: upload_to_sharepoint
    type: boolean
    default: false
  - name: repo
    default: self
  - name: tests_run_timeout
    type: number
    default: 20
  - name: sonar_project_key
  - name: sonar_project_name
  - name: run_sonarcloud_analysis
    type: boolean
    default: true
  - name: run_accessibility_tests
    type: boolean
    default: false

jobs:
  - job: 'RunAutomatedE2ETests'
    displayName: 'Run Automated E2E Tests'
    timeoutInMinutes: ${{ parameters.tests_run_timeout }}
    steps:
      - script: |
          echo "Installing PowerShell"
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          source /etc/os-release
          wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
        displayName: 'Install PowerShell'
        
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $day = $(Get-Date -Format dddd);
            Write-Host "##vso[task.setvariable variable=DayOfWeek]$day"

      # Install Java 21 for SonarCloud
      - ${{ if parameters.run_sonarcloud_analysis }}:
          - script: |
              echo "Installing OpenJDK 21..."
              sudo apt-get update
              sudo apt-get install -y openjdk-21-jdk
              # Verify installation
              java -version
              # Set JAVA_HOME for this pipeline
              JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
              echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME"
              echo "JAVA_HOME set to: $JAVA_HOME"
            displayName: 'Install Java 21 for SonarCloud'

      # sonar cloud code analysis configuration
      - ${{ if parameters.run_sonarcloud_analysis }}:
          - template: ../steps/codeanalysis/cli_prepare_analysis_configuration.yaml
            parameters:
              project_key: ${{ parameters.sonar_project_key }}
              project_name: ${{ parameters.sonar_project_name }}

      - template: ../steps/automationtests/run_e2e_test.yaml
        parameters:
          platform: ${{ parameters.platform }}
          browser: ${{ parameters.browser }}
          mobile_os: ${{ parameters.mobile_os }}
          android_device: ${{ parameters.android_device }}
          ios_device: ${{ parameters.ios_device }}
          run_accessibility_tests: ${{ parameters.run_accessibility_tests }}
          reportDirectory: ${{ parameters.reportDirectory }}
          timeout: ${{ parameters.tests_run_timeout }}
          repo: ${{ parameters.repo }}

      # sonar cloud run code analysis
      - ${{ if parameters.run_sonarcloud_analysis }}:
          - template: ../steps/codeanalysis/run_code_analysis.yaml
          - template: ../steps/codeanalysis/publish_quality_gate_result.yaml

      # set to default by false, will be set to true in the main nightly run pipeline
      # this is to prevent exporting the report to SharePoint with every automated run.
      - ${{ if parameters.upload_to_sharepoint }}:
          - template: ../steps/sharepoint/upload_to_sharepoint.yaml
            parameters:
              sharepoint_drive_id: $(sharepoint_drive_id)
              sharepoint_target_folder: $(sharepoint_target_folder)
              source_folder: $(System.DefaultWorkingDirectory)/${{ parameters.reportDirectory }}
