parameters:
  - name: checkout
    default: true

steps:
  - checkout: self
    condition: ${{ parameters.checkout }} 
  - task: "DotNetCoreCLI@2"
    displayName: 'Building Solution'
    inputs:
      command: "build"
      projects: '$(solution)'